- Sorting Algorithms/HeapSort.cpp
added the heap sort algorithm implemented in c++
> added HeapSort

- Arrays/Hotel Bookings Possible
- Arrays/Min Steps in Infinite Grid
- Hotel Booking Possible Problem<br/>
- Min Steps In Infinite Grid Problem<br/>
> Added problems related to array which are asked in Interview

- Linked List/Palindrome_Linkedlist.py
Added a program to check whether a Linkedlist is a plaindrome or not.
> Check if linkedlist is palindrome

- Searching/BinarySearch.cpp
- Searching/FibonacciSearch.cpp
- Searching/LinearSearch.cpp
- Searching/TernarySearch.cpp
> Searching Algorithms

- Linked List/function-to-reverse-node-of-linked-list.cpp
This program is in CPP to reverse a node of linked list.
> Function to reverse a Linked list

- Linked List/Rearrange a linked list.cpp
Rearrange a linked list such that all even and odd positioned nodes are together
> Rearrange a linked list 

- SPOJ_LIST/CANDY.cpp
- SPOJ_LIST/FACEFRND.cpp
Solution to spoj adhoc problems i.e- CANDY  and FACEFRND are added
> Added two SPOJ problem solutions

- Linked List/int-LL-counter.cpp
How many times does an integer occur in the Linked List?
> Count integer occurances in a Linked List

- Stack/postFix.c
This file will be useful for doing post fix.
> Added postFix file in Stack

- SPOJ_LIST/min_smoke.cpp
Added solution for MInimum smoke DP Solution in SPOJ_LIST
> Added Min_smoke.cpp solution in Spoj_list

- circular-queue.cpp
- queue/level-order-traversal-in-spiral-form.cpp
- queue/sliding-window-maximum.cpp
Operations on Circular Queue:
Front:Get the front item from queue.
Rear: Get the last item from queue.
enQueue(value) This function is used to insert an element into the circular queue. In a circular queue, the new element is always inserted at Rear position.
> circular-queue

- Arrays/Array_WavePrint.cpp
- Arrays/array_spiral_print.cpp
- Arrays/leftRotateArray.cpp
- Arrays/maxSubArraySum.cpp
- Searching/StaircaseSearch.cpp
1. Arrays/Array_WavePrint.cpp
This Program allows to wave print an array in c++
2. Arrays/array_spiral_print.cpp
This Program allows to spiral print an array in c++
3. Arrays/leftRotateArray.cpp
This Program allows to left rotate an array with any input
4. Arrays/maxSubArraySum.cpp
This Program outputs the maximum sub array sum using kadanes algorithm
5. Searching/StaircaseSearch.cpp
This Program allows to staircase search a 2d array
> Added 4 in Arrays and 1 in Searching

- odd_even_linked_list.cpp
Added odd even linked list of leetcode
> Added odd even linked list of leetcode

- Binary Tree/countBalancedNodes.cpp
#4 Adding a cpp program to count the number of balanced nodes in a binary tree.
> adding a cpp program

- Linked List/copy_list_with_random_pointer.cpp
Added clone a linked list with random pointer
> Added clone list with random pointer

- Problem Solving/Power_of_2_in_log(n).py
Added code to very efficiently check whether a number is a power of 2 or not, which has applications in various problems.
> Created New Folder Problem Solving and added Power_of_2 code in log(n) time

- Dynamic Programming/Climbing_Stairs_DP.py
Classical DP problem climbing stairs, very important for someone to do who is getting started with dynamic programming.
> Created Dynamic Programming Folder and add Climbing_Stairs_DP problem code.

- Stack/Valid Parentheses.cpp
Added valid parentheses solution
> Added valid parentheses solution

- 2_STRINGS/String6_Count Occurences of each char in str.py
Added the python Program to count the number of occurences of characters in a string.
> Create String6_Count Occurences of each char in str.py

- Stack/queue_from_stacks.py
> Add Queue from Stacks

- Dynamic Programming/Coin_Change_DP.py
Very important problem based on DP, asked in several interviews.
> Added Coin Change DP problem code

- 2_STRINGS/sort_the_strings.cpp
- 2_STRINGS/string_compression.cpp
- Arrays/target_pair_sum.cpp
Strings:
1. Sort the Strings
2. String Compression (Consecutive Characters)
Arrays:
1. Target Pair Sum (Finds a Pair in an Array equal to the given target)
> Added 2 in Strings and 1 in Arrays

- Linked List/reverse_linked_list_in_given_group_size.cpp
Reverse a linked list in groups of given size.
> linked list issue #15

- Stack/Backspace String Compare.cpp
Added Backspace String compare solution of stack
> Added Backspace String compare solution of stack

- SPOJ_LIST/CEQU.cpp
Added solution of CEQU problem
> Add CEQU solution

- 2_STRINGS/Naive Pattern Searching.cpp
- 2_STRINGS/String8_Remove Odd indexed characters
Added String Searching Algorithm
> Added String Pattern Search Algorithm - Naive Algorithm

- Stack/Next Greater Element.cpp
Added Next Greater Element Solution
> Added Next Greater Element Solution

- Binary Tree/Binary Tree Level Order Traversal.cpp
- Linked List/Odd Even Linked List.cpp
Please find the ques below
https://leetcode.com/problems/odd-even-linked-list/
> Create Odd Even Linked List.cpp

- Dynamic Programming/Longest palindrome.cpp
Find Longest palindrome using DP.
> Added: Longest Palindrome

- Dynamic Programming/EqualSumPartition_DP.py
Added a sum on Dynamic programming
given a list of numbers we have to find whether that list can be partitioned into two parts such that their sum is equal
> Added a sum on DP EqualSumPartition.py

- SPOJ_LIST/ADAAPHID.cpp
- SPOJ_LIST/ADACROP.cpp
- SPOJ_LIST/ALLIN1.cpp
- SPOJ_LIST/KOILINE.cpp
- SPOJ_LIST/ORDERSET.cpp
- SPOJ_LIST/TWIST.cpp
> Added solutions to 6 treap SPOJ problems

- Arrays/kadanes-algo.cpp
- Arrays/majority-element.cpp
- Arrays/reverse-array-in-grp.cpp
Added 3 important array code. I just started contributing to open source, I hope my Pr would get merged
> Added-code

- Problem Solving/guessing_game.rs
Classic Guessing Game in Rust
The computer generates a random number in the range 1 -100
If both the numbers match user wins else computer gives another chance until the user wins 😀😀
> Guessing Game in Rust

- Binary Tree/Binary Tree - Print k distant node from given target node.cpp
Given a root Node and kth level. Prints the k distant node from given node.
>  Print k distant node from given target node

- Arrays/Maximum Xor of two elements.cpp
- Graphs/Longest Cable Length.cpp
Efficient time Complexity Solution for max XOR in elements of array.
> Max XOR of two elements in array

- Problem Solving/Pattern.cpp
Explanation : Catch the pattern for the corresponding input and print it accordingly.
> Pattern based Problem Solving Question

- EffecientRecursuionFibonacci.py
a Fibonacci recursive algorithm which is very fast than the traditional recursive solution
> added a very efficient recursive Fibonacci program

- Divide-and-conquer/TowerOfHanoi.java
interactive solution for the tower of Hanoi this code gives the steps to solve the tower of Hanoi of any give number of disks in a stack
> interactive solution for Tower of Hanoi

- MorseCode.java
this code gives the morse code for a given string
> Morse Code Encoding for a given string

- greedy/sum-of-two-numbers.java
java code to find if any pair of numbers in the array adds to the given target in O(n)
> competitive programming question

- hashing/count-pairs-with-given-sum.java
I MADE THE NECCESARY CHANGE SO ONCE REVIEW THE CODE,IT HAS BEEN COMPLIED SUCCESSFULLY
> PLZ CHECK THE NECCASARY CHANGE MADE AND REVIEW IT

- Breadth first search/Binary Tree Level Order Traversal.cpp
> PLZ CHECK THE CHANGES WHICH I HAD DONE

- Strings/smallest-window-in-a-string-containing-all-the-characters-of-another-string.java
> PLZ CHECK THE UPDATED CODE

- Arrays/UsingArraysConvertSelectionSortAsStable.java
A sorting algorithm is said to be stable if two objects with equal or same keys appear in the same order in sorted output as they appear in the input array to be sorted.
Any comparison based sorting algorithm which is not stable by nature can be modified to be stable by changing the key comparison operation so that the comparison of two keys considers position as a factor for objects with equal key or by tweaking it in a way such that its meaning doesn’t change and it becomes stable as well.
Selection sort works by finding the minimum element and then inserting it in its correct position by swapping with the element which is in the position of this minimum element. This is what makes it unstable.
Swapping might impact in pushing a key (imagine X)to a position greater than the key(Imagine …
> Using Arrays convert unstable selection sort as stable selection sort

- Stack/TowerOfHanoi.java
this program give the steps to solve the tower of Hanoi problem for a given number of disk
> added an interactive solution for tower of Hanoi

- Problem Solving/SmartRanking.java
this algorithm can be used in two way either for ranking scores or for ranking positions
this gives the rank according to the users choice either in ascending or in descending
> Added Smart ranking Algorithm which gives ranks to the elements

- Trie_Interview_Questions/bottomUpTraversal_in_Trie.cpp
- Trie_Interview_Questions/combination_of_words.cpp
- Trie_Interview_Questions/count_No_of_words_withgivenprefix.cpp
- Trie_Interview_Questions/memoryOptimizedTrie.cpp
- Trie_Interview_Questions/trie_using_oopandpointers.cpp
> add Trie Questions

- trees/lowest_common_ancestor.cpp
I've added an important question on trees in the repository!
Hope you'll like it !!
Please let me know if any changes are required :)
> Adding Code of Tree Data Structure

- Linked List/MergePointoftwolinkedlists.c
Added a solution to find the merge point of two linked lists
> add MergePointoftwolinkedlists

- Strings/pattern_pyramid_vertical_string.py
I have added python program for string pattern. It takes string as input and gives character pattern in vertical pyramid as output.
> added vertical_pyramid_pattern_string in python

- Arrays/Wave Array.cpp
Wave Array.cpp is an array problem asked in FAANG. #8
> Wave Array.cpp FAANG problem

- Strings/dynamic_string_pyramid.java
i have added program in java, that this program can print any string into the form of a standatd pyramid.
> Created dynamic_string_pyramid.java

- Linked List/priority_queue_using_linked_list.cpp
- Linked List/reverse_linked_list_in_given_group_size.cpp
- queue/reverse_queue_using_other_queue.cpp
priority_queue_using_linked_list
> issue #15 

- Divide-and-conquer/k-th-element-of-two-sorted-array.java
> made efficent changes

- Stack/Valid Parentheses.cpp
> made efficient change

- Sorting/bubble_sort.cpp
> made efficent change

- trees/bottom_view_of_binary_tree.cpp
- trees/top_view_of_binary_tree.cpp
Top and Bottom View of Tree are important interview coding questions and are not present in the repo
> Adding Solutions to Interview Questions in C++
